version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest public.ecr.aws/h1c3m4v4/youtube:latest
  post_build:
    commands:
      - docker push public.ecr.aws/h1c3m4v4/youtube:latest
      - printf '[{"name":"helloWorld","imageUri":"%s"}]' public.ecr.aws/h1c3m4v4/youtube:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
